-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0756
--   at:        2018-12-01 14:10:49 AMT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE academies (
    academy_id      NUMBER(10) NOT NULL,
    arena           VARCHAR2(50 CHAR),
    chairman        VARCHAR2(50 CHAR),
    acad_location   VARCHAR2(50 CHAR),
    acad_manager    VARCHAR2(50 CHAR)
);

ALTER TABLE academies ADD CONSTRAINT academies_pk PRIMARY KEY ( academy_id );

CREATE TABLE agents (
    agent_id      NUMBER(10) NOT NULL,
    f_name        VARCHAR2(50 CHAR),
    l_name        VARCHAR2(50 CHAR),
    nationality   VARCHAR2(50 CHAR)
);

ALTER TABLE agents ADD CONSTRAINT agents_pk PRIMARY KEY ( agent_id );

CREATE TABLE coaches (
    employee_id     NUMBER(10) NOT NULL,
    nickname        VARCHAR2(50 CHAR),
    coach_type      VARCHAR2(50 CHAR),
    teams_team_id   NUMBER(10)
);

ALTER TABLE coaches ADD CONSTRAINT coaches_pk PRIMARY KEY ( employee_id );

CREATE TABLE commentators (
    commentator_id    NUMBER(10) NOT NULL,
    com_name          VARCHAR2(50 CHAR),
    spoken_language   VARCHAR2(50 CHAR),
    start_date        DATE,
    tvs_tv_id         NUMBER(10)
);

ALTER TABLE commentators ADD CONSTRAINT commentators_pk PRIMARY KEY ( commentator_id );

CREATE TABLE employees (
    employee_id   NUMBER(10) NOT NULL,
    gender        CHAR(1 CHAR),
    start_date    DATE,
    f_name        VARCHAR2(50 CHAR),
    l_name        VARCHAR2(50 CHAR),
    salary        NUMBER(10),
    nationality   VARCHAR2(50 CHAR)
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id );

CREATE TABLE fan_clubs (
    fan_club_id     NUMBER(10) NOT NULL,
    website         VARCHAR2(50 CHAR),
    song            VARCHAR2(50 CHAR),
    country         VARCHAR2(50 CHAR),
    members         NUMBER(10),
    emblem          VARCHAR2(50 CHAR),
    telephone       NUMBER(10),
    secretary       VARCHAR2(50 CHAR),
    teams_team_id   NUMBER(10) NOT NULL
);

ALTER TABLE fan_clubs ADD CONSTRAINT fan_clubs_pk PRIMARY KEY ( fan_club_id );

CREATE TABLE fixture (
    fixture_id       NUMBER(10) NOT NULL,
    fixture_date     DATE,
    teams_team_id    NUMBER(10) NOT NULL,
    teams_team_id1   NUMBER(10) NOT NULL
);

ALTER TABLE fixture ADD CONSTRAINT fixture_pk PRIMARY KEY ( fixture_id );

CREATE TABLE goals (
    players_employee_id1   NUMBER(10) NOT NULL,
    matches_match_id       NUMBER(10) NOT NULL,
    players_employee_id    NUMBER(10),
    goals_id               NUMBER NOT NULL
);

CREATE UNIQUE INDEX goals__idx ON
    goals (
        players_employee_id
    ASC );

ALTER TABLE goals ADD CONSTRAINT goals_pk PRIMARY KEY ( goals_id );

CREATE TABLE individual (
    owner_id   NUMBER(10) NOT NULL,
    f_name     VARCHAR2(30 CHAR),
    l_name     VARCHAR2(30 CHAR)
);

ALTER TABLE individual ADD CONSTRAINT individual_pk PRIMARY KEY ( owner_id );

CREATE TABLE injuries (
    injury_id           NUMBER(10) NOT NULL,
    injury_type         VARCHAR2(50 CHAR),
    injury_name         VARCHAR2(50 BYTE),
    expected_rec_date   DATE
);

ALTER TABLE injuries ADD CONSTRAINT injuries_pk PRIMARY KEY ( injury_id );

CREATE TABLE leagues (
    leagues_id         NUMBER(10) NOT NULL,
    current_champion   VARCHAR2(50 CHAR),
    team_number        NUMBER(10),
    legaue_name        VARCHAR2(50 CHAR),
    website            VARCHAR2(50 CHAR),
    country            VARCHAR2(50 CHAR),
    ceo                VARCHAR2(50 CHAR),
    founded            DATE
);

ALTER TABLE leagues ADD CONSTRAINT leagues_pk PRIMARY KEY ( leagues_id );

CREATE TABLE leagues_tvs (
    leagues_leagues_id   NUMBER(10) NOT NULL,
    tvs_tv_id            NUMBER(10) NOT NULL,
    contract_date        DATE,
    contract_type        VARCHAR2(50 CHAR)
);

ALTER TABLE leagues_tvs ADD CONSTRAINT leagues_tvs_pk PRIMARY KEY ( leagues_leagues_id,
                                                                    tvs_tv_id );

CREATE TABLE legal_entity (
    owner_id       NUMBER(10) NOT NULL,
    compamy_name   VARCHAR2(30 CHAR),
    ident_number   NUMBER(10,2),
    stock_name     VARCHAR2(30 CHAR)
);

ALTER TABLE legal_entity ADD CONSTRAINT legal_entity_pk PRIMARY KEY ( owner_id );

CREATE TABLE man_firm (
    man_firm_id     NUMBER(10,2) NOT NULL,
    stock_name      VARCHAR2(15 CHAR),
    man_firm_name   VARCHAR2(30 CHAR),
    capital         NUMBER(10,2)
);

ALTER TABLE man_firm ADD CONSTRAINT man_firm_pk PRIMARY KEY ( man_firm_id );

CREATE TABLE matches (
    match_id                      NUMBER(10) NOT NULL,
    match_date                    DATE,
    minutes_played                NUMBER(10,2),
    weather                       VARCHAR2(50 CHAR),
    fixture_fixture_id            NUMBER(10),
    stadiums_stadium_id           NUMBER(10) NOT NULL,
    leagues_leagues_id            NUMBER(10) NOT NULL,
    commentators_commentator_id   NUMBER(10),
    referees_referees_id          NUMBER(10) NOT NULL
);

CREATE UNIQUE INDEX matches__idx ON
    matches (
        fixture_fixture_id
    ASC );

CREATE UNIQUE INDEX matches__idxv1 ON
    matches (
        commentators_commentator_id
    ASC );

CREATE UNIQUE INDEX matches__idxv2 ON
    matches (
        referees_referees_id
    ASC );

ALTER TABLE matches ADD CONSTRAINT matches_pk PRIMARY KEY ( match_id );

CREATE TABLE owners (
    owner_id           NUMBER(10) NOT NULL,
    f_name             VARCHAR2(50 CHAR),
    l_name             VARCHAR2(50 CHAR),
    share_percentage   NUMBER(10,2),
    invested           NUMBER(10,2)
);

ALTER TABLE owners ADD CONSTRAINT owners_pk PRIMARY KEY ( owner_id );

CREATE TABLE players (
    employee_id       NUMBER(10) NOT NULL,
    player_number     NUMBER(10),
    weight            NUMBER(10,2),
    height            NUMBER(10,2),
    national_team     VARCHAR2(50 CHAR),
    start_date        DATE,
    agent_salary      NUMBER(10),
    agents_agent_id   NUMBER(10),
    teams_team_id     NUMBER(10),
    goals_goals_id    NUMBER
);

CREATE UNIQUE INDEX players__idx ON
    players (
        goals_goals_id
    ASC );

ALTER TABLE players ADD CONSTRAINT players_pk PRIMARY KEY ( employee_id );

CREATE TABLE players_injuries (
    players_employee_id   NUMBER(10) NOT NULL,
    injuries_injury_id    NUMBER(10) NOT NULL,
    status                VARCHAR2(50 CHAR),
    injury_date           DATE
);

ALTER TABLE players_injuries ADD CONSTRAINT players_injuries_pk PRIMARY KEY ( players_employee_id,
                                                                              injuries_injury_id );

CREATE TABLE players_matches (
    players_employee_id   NUMBER(10) NOT NULL,
    matches_match_id      NUMBER(10) NOT NULL,
    key_passes            NUMBER(10),
    shots                 NUMBER(10),
    minutes_played        NUMBER(10),
    pass_accuracy         NUMBER(10),
    dribbles              NUMBER(10),
    aerials_won           NUMBER(10),
    saves                 NUMBER(10),
    shots_on_t            NUMBER(10),
    tackles               NUMBER(10),
    xa                    NUMBER(10),
    xg                    NUMBER(10),
    red_cards             NUMBER(10),
    yellow_cards          NUMBER(10),
    fouls                 NUMBER(10)
);

ALTER TABLE players_matches ADD CONSTRAINT players_matches_pk PRIMARY KEY ( players_employee_id,
                                                                            matches_match_id );

CREATE TABLE players_sponsors (
    players_employee_id   NUMBER(10) NOT NULL,
    sponsors_sponsor_id   NUMBER(10) NOT NULL,
    end_date              DATE,
    start_date            DATE
);

ALTER TABLE players_sponsors ADD CONSTRAINT players_sponsors_pk PRIMARY KEY ( players_employee_id,
                                                                              sponsors_sponsor_id );

CREATE TABLE positions (
    position_id   NUMBER(10) NOT NULL,
    parent_type   VARCHAR2(50 CHAR),
    sub_type      VARCHAR2(50 CHAR)
);

ALTER TABLE positions ADD CONSTRAINT positions_pk PRIMARY KEY ( position_id );

CREATE TABLE positions_players (
    positions_position_id   NUMBER(10) NOT NULL,
    players_employee_id     NUMBER(10) NOT NULL
);

ALTER TABLE positions_players ADD CONSTRAINT positions_players_pk PRIMARY KEY ( positions_position_id,
                                                                                players_employee_id );

CREATE TABLE presidents (
    employee_id      NUMBER(10) NOT NULL,
    years_on_board   NUMBER(5)
);

ALTER TABLE presidents ADD CONSTRAINT presidents_pk PRIMARY KEY ( employee_id );

CREATE TABLE referees (
    referees_id     NUMBER(10) NOT NULL,
    referee_name    VARCHAR2(50 CHAR),
    certification   VARCHAR2(50 CHAR),
    birth_date      DATE,
    start_date      DATE
);

ALTER TABLE referees ADD CONSTRAINT referees_pk PRIMARY KEY ( referees_id );

CREATE TABLE scouts (
    employee_id     NUMBER(10) NOT NULL,
    scout_type      VARCHAR2(50 CHAR),
    country         VARCHAR2(50 CHAR),
    teams_team_id   NUMBER(10)
);

ALTER TABLE scouts ADD CONSTRAINT scouts_pk PRIMARY KEY ( employee_id );

CREATE TABLE social_media (
    sm_id                 NUMBER(10,2) NOT NULL,
    twitter               VARCHAR2(30 CHAR),
    facebook              VARCHAR2(30 CHAR),
    subscribers_count     NUMBER(10,2),
    instagram             VARCHAR2(30 CHAR),
    players_employee_id   NUMBER(10) NOT NULL
);

ALTER TABLE social_media ADD CONSTRAINT social_media_pk PRIMARY KEY ( sm_id );

CREATE TABLE sponsors (
    sponsor_id        NUMBER(10) NOT NULL,
    full_name         VARCHAR2(50 CHAR),
    business_sector   VARCHAR2(50 CHAR)
);

ALTER TABLE sponsors ADD CONSTRAINT sponsors_pk PRIMARY KEY ( sponsor_id );

CREATE TABLE stadiums (
    stadium_id         NUMBER(10) NOT NULL,
    founded_in         VARCHAR2(50 CHAR),
    address            VARCHAR2(50 CHAR),
    stsdium_capacity   NUMBER(10)
);

ALTER TABLE stadiums ADD CONSTRAINT stadiums_pk PRIMARY KEY ( stadium_id );

CREATE TABLE tactics (
    tactics_id   NUMBER(10) NOT NULL,
    title        VARCHAR2(50 CHAR),
    formation    VARCHAR2(50 CHAR)
);

ALTER TABLE tactics ADD CONSTRAINT tactics_pk PRIMARY KEY ( tactics_id );

CREATE TABLE teams (
    team_id                  NUMBER(10) NOT NULL,
    team_name                VARCHAR2(50 CHAR),
    team_value               NUMBER(10),
    logo                     VARCHAR2(50 CHAR),
    founded                  DATE,
    anthem                   VARCHAR2(50 CHAR),
    academies_academy_id     NUMBER(10),
    leagues_leagues_id       NUMBER(10),
    presidents_employee_id   NUMBER(10) NOT NULL
);

CREATE UNIQUE INDEX teams__idx ON
    teams (
        presidents_employee_id
    ASC );

CREATE UNIQUE INDEX teams__idxv1 ON
    teams (
        academies_academy_id
    ASC );

ALTER TABLE teams ADD CONSTRAINT teams_pk PRIMARY KEY ( team_id );

CREATE TABLE teams_matches (
    teams_team_id      NUMBER(10) NOT NULL,
    matches_match_id   NUMBER(10) NOT NULL,
    posession          NUMBER(10,2),
    total_passes       NUMBER(10),
    corners            NUMBER(10),
    xa                 NUMBER(10),
    xg                 NUMBER
);

ALTER TABLE teams_matches ADD CONSTRAINT teams_matches_pk PRIMARY KEY ( teams_team_id,
                                                                        matches_match_id );

CREATE TABLE teams_owners (
    teams_team_id     NUMBER(10) NOT NULL,
    owners_owner_id   NUMBER(10) NOT NULL
);

ALTER TABLE teams_owners ADD CONSTRAINT teams_owners_pk PRIMARY KEY ( teams_team_id,
                                                                      owners_owner_id );

CREATE TABLE teams_sponsors (
    sponsors_sponsor_id   NUMBER(10) NOT NULL,
    teams_team_id         NUMBER(10) NOT NULL
);

ALTER TABLE teams_sponsors ADD CONSTRAINT teams_sponsors_pk PRIMARY KEY ( sponsors_sponsor_id,
                                                                          teams_team_id );

CREATE TABLE teams_tactics (
    tactics_tactics_id   NUMBER(10) NOT NULL,
    teams_team_id        NUMBER(10) NOT NULL
);

ALTER TABLE teams_tactics ADD CONSTRAINT teams_tactics_pk PRIMARY KEY ( tactics_tactics_id,
                                                                        teams_team_id );

CREATE TABLE tickets (
    tickets_id         NUMBER(10) NOT NULL,
    ticket_row         NUMBER(10),
    seat               NUMBER(10),
    sector             NUMBER(10),
    status             VARCHAR2(50 CHAR),
    price              NUMBER(10,2),
    matches_match_id   NUMBER(10) NOT NULL
);

ALTER TABLE tickets ADD CONSTRAINT tickets_pk PRIMARY KEY ( tickets_id );

CREATE TABLE transfers (
    transfer_id           NUMBER(10) NOT NULL,
    amount                NUMBER(10),
    transfer_date         DATE,
    players_employee_id   NUMBER(10) NOT NULL,
    teams_team_id         NUMBER(10) NOT NULL,
    teams_team_id1        NUMBER(10) NOT NULL
);

CREATE UNIQUE INDEX transfers__idx ON
    transfers (
        players_employee_id
    ASC );

ALTER TABLE transfers ADD CONSTRAINT transfers_pk PRIMARY KEY ( transfer_id );

CREATE TABLE tvs (
    tv_id      NUMBER(10) NOT NULL,
    tv_name    VARCHAR2(50 CHAR),
    audience   NUMBER(10),
    country    VARCHAR2(50 CHAR),
    founded    DATE
);

ALTER TABLE tvs ADD CONSTRAINT tvs_pk PRIMARY KEY ( tv_id );

CREATE TABLE uniforms (
    firm                   VARCHAR2(50 CHAR) NOT NULL,
    color_scheme           VARCHAR2(50 CHAR),
    fabric                 VARCHAR2(50 CHAR),
    teams_team_id          NUMBER(10) NOT NULL,
    man_firm_man_firm_id   NUMBER(10,2)
);

ALTER TABLE uniforms ADD CONSTRAINT uniforms_pk PRIMARY KEY ( teams_team_id,
                                                              firm );

ALTER TABLE coaches
    ADD CONSTRAINT coaches_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE coaches
    ADD CONSTRAINT coaches_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE commentators
    ADD CONSTRAINT commentators_tvs_fk FOREIGN KEY ( tvs_tv_id )
        REFERENCES tvs ( tv_id );

ALTER TABLE fan_clubs
    ADD CONSTRAINT fan_clubs_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE fixture
    ADD CONSTRAINT fixture_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE fixture
    ADD CONSTRAINT fixture_teams_fkv2 FOREIGN KEY ( teams_team_id1 )
        REFERENCES teams ( team_id );

ALTER TABLE goals
    ADD CONSTRAINT goals_matches_fk FOREIGN KEY ( matches_match_id )
        REFERENCES matches ( match_id );

ALTER TABLE goals
    ADD CONSTRAINT goals_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE goals
    ADD CONSTRAINT goals_players_fkv2 FOREIGN KEY ( players_employee_id1 )
        REFERENCES players ( employee_id );

ALTER TABLE individual
    ADD CONSTRAINT individual_owners_fk FOREIGN KEY ( owner_id )
        REFERENCES owners ( owner_id );

ALTER TABLE leagues_tvs
    ADD CONSTRAINT leagues_tvs_leagues_fk FOREIGN KEY ( leagues_leagues_id )
        REFERENCES leagues ( leagues_id );

ALTER TABLE leagues_tvs
    ADD CONSTRAINT leagues_tvs_tvs_fk FOREIGN KEY ( tvs_tv_id )
        REFERENCES tvs ( tv_id );

ALTER TABLE legal_entity
    ADD CONSTRAINT legal_entity_owners_fk FOREIGN KEY ( owner_id )
        REFERENCES owners ( owner_id );

ALTER TABLE matches
    ADD CONSTRAINT matches_commentators_fk FOREIGN KEY ( commentators_commentator_id )
        REFERENCES commentators ( commentator_id );

ALTER TABLE matches
    ADD CONSTRAINT matches_fixture_fk FOREIGN KEY ( fixture_fixture_id )
        REFERENCES fixture ( fixture_id );

ALTER TABLE matches
    ADD CONSTRAINT matches_leagues_fk FOREIGN KEY ( leagues_leagues_id )
        REFERENCES leagues ( leagues_id );

ALTER TABLE matches
    ADD CONSTRAINT matches_referees_fk FOREIGN KEY ( referees_referees_id )
        REFERENCES referees ( referees_id );

ALTER TABLE matches
    ADD CONSTRAINT matches_stadiums_fk FOREIGN KEY ( stadiums_stadium_id )
        REFERENCES stadiums ( stadium_id );

ALTER TABLE players
    ADD CONSTRAINT players_agents_fk FOREIGN KEY ( agents_agent_id )
        REFERENCES agents ( agent_id );

ALTER TABLE players
    ADD CONSTRAINT players_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE players
    ADD CONSTRAINT players_goals_fk FOREIGN KEY ( goals_goals_id )
        REFERENCES goals ( goals_id );

ALTER TABLE players_injuries
    ADD CONSTRAINT players_injuries_injuries_fk FOREIGN KEY ( injuries_injury_id )
        REFERENCES injuries ( injury_id );

ALTER TABLE players_injuries
    ADD CONSTRAINT players_injuries_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE players_matches
    ADD CONSTRAINT players_matches_matches_fk FOREIGN KEY ( matches_match_id )
        REFERENCES matches ( match_id );

ALTER TABLE players_matches
    ADD CONSTRAINT players_matches_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE players_sponsors
    ADD CONSTRAINT players_sponsors_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE players_sponsors
    ADD CONSTRAINT players_sponsors_sponsors_fk FOREIGN KEY ( sponsors_sponsor_id )
        REFERENCES sponsors ( sponsor_id );

ALTER TABLE players
    ADD CONSTRAINT players_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE positions_players
    ADD CONSTRAINT positions_players_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE positions_players
    ADD CONSTRAINT positions_players_positions_fk FOREIGN KEY ( positions_position_id )
        REFERENCES positions ( position_id );

ALTER TABLE presidents
    ADD CONSTRAINT presidents_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE scouts
    ADD CONSTRAINT scouts_employees_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE scouts
    ADD CONSTRAINT scouts_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE social_media
    ADD CONSTRAINT social_media_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE teams
    ADD CONSTRAINT teams_academies_fk FOREIGN KEY ( academies_academy_id )
        REFERENCES academies ( academy_id );

ALTER TABLE teams
    ADD CONSTRAINT teams_leagues_fk FOREIGN KEY ( leagues_leagues_id )
        REFERENCES leagues ( leagues_id );

ALTER TABLE teams_matches
    ADD CONSTRAINT teams_matches_matches_fk FOREIGN KEY ( matches_match_id )
        REFERENCES matches ( match_id );

ALTER TABLE teams_matches
    ADD CONSTRAINT teams_matches_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE teams_owners
    ADD CONSTRAINT teams_owners_owners_fk FOREIGN KEY ( owners_owner_id )
        REFERENCES owners ( owner_id );

ALTER TABLE teams_owners
    ADD CONSTRAINT teams_owners_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE teams
    ADD CONSTRAINT teams_presidents_fk FOREIGN KEY ( presidents_employee_id )
        REFERENCES presidents ( employee_id );

ALTER TABLE teams_sponsors
    ADD CONSTRAINT teams_sponsors_sponsors_fk FOREIGN KEY ( sponsors_sponsor_id )
        REFERENCES sponsors ( sponsor_id );

ALTER TABLE teams_sponsors
    ADD CONSTRAINT teams_sponsors_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE teams_tactics
    ADD CONSTRAINT teams_tactics_tactics_fk FOREIGN KEY ( tactics_tactics_id )
        REFERENCES tactics ( tactics_id );

ALTER TABLE teams_tactics
    ADD CONSTRAINT teams_tactics_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE tickets
    ADD CONSTRAINT tickets_matches_fk FOREIGN KEY ( matches_match_id )
        REFERENCES matches ( match_id );

ALTER TABLE transfers
    ADD CONSTRAINT transfers_players_fk FOREIGN KEY ( players_employee_id )
        REFERENCES players ( employee_id );

ALTER TABLE transfers
    ADD CONSTRAINT transfers_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

ALTER TABLE transfers
    ADD CONSTRAINT transfers_teams_fkv2 FOREIGN KEY ( teams_team_id1 )
        REFERENCES teams ( team_id );

ALTER TABLE uniforms
    ADD CONSTRAINT uniforms_man_firm_fk FOREIGN KEY ( man_firm_man_firm_id )
        REFERENCES man_firm ( man_firm_id );

ALTER TABLE uniforms
    ADD CONSTRAINT uniforms_teams_fk FOREIGN KEY ( teams_team_id )
        REFERENCES teams ( team_id );

CREATE SEQUENCE goals_goals_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER goals_goals_id_trg BEFORE
    INSERT ON goals
    FOR EACH ROW
    WHEN ( new.goals_id IS NULL )
BEGIN
    :new.goals_id := goals_goals_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            38
-- CREATE INDEX                             8
-- ALTER TABLE                             89
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
